### ISSUE TITLE
Need to disable globus online registration during gridftp installation

### ISSUE THREAD

**Issue by ncarenton** [ESGF/esgf-installer#133]
Hi,

Some centers which are willing to run a GridFTP server as part of their ESGF node disagree with the globus online registration part which does require to store credentials on globus servers. Externalizing credentials storage on a closed source platform is a no go. Could we disable this part or make it optional?

Thanks

**Comment by lukaszlacinski** [comment]
Pull request, https://github.com/ESGF/esgf-installer/pull/150, resolves the issue.
