### ISSUE TITLE
esg-node --update-apache-conf should not be a manual step after a node upgrade

### ISSUE THREAD

**Issue by ncarenton** [ESGF/esgf-installer#136]
esg-node --update-apache-conf should not be a manual step after a node upgrade

**Comment by sashakames** [comment]
More recently it was made automatic after every restart.  Has that been addressed?

**Comment by sashakames** [comment]
Update: addressing this to be automated during install time when a new version of the conf is released.

**Comment by sashakames** [comment]
We have implemented versioning of the conf script that updates when there is a new version.
