### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by omula** [ESGF/esgf-installer#152]
I am trying to install ESGF and although the installation seems to have succeed by it is not working. I am getting an error 500 while accessing with the web browser the root url. It is highly possible that I have done something wrong. However,  it looks a bit difficult to try to find out what is wrong because the installer doesn't stop when there's an error. As you can see below I had multiple error messages which i don't know how important they are.

I selected not install globus. Is it mandatory?

```
touch: cannot touch `/usr/local/globus/esg_esg-node_installed': No such file or directory
cp: cannot create regular file `/var/lib/globus-connect-server/myproxy-ca/cacert.pem': No such file or directory
cp: cannot create regular file `/var/lib/globus-connect-server/myproxy-ca/private/cakey.pem': No such file or directory
cp: cannot create regular file `/var/lib/globus-connect-server/myproxy-ca/': No such file or directory
cp: cannot create regular file `/etc/grid-security/certificates/': Is a directory
Local installation of certs complete.
```

I am doing the installation for testing, do I need an IDP?

```
Downloading ROOT application from http://dist.ceda.ac.uk/esgf/dist/ROOT.tgz
 ==> /usr/local/src/esgf/workbench/esg/ROOT.tgz is up to date
unpacking ROOT.tgz...
ROOT application "installed"
Cleared tomcat cache... 
chmod: cannot access `/esg/config/esgf_idp_static.xml': No such file or directory
starting services... (45)
Running startup hooks...
chmod: cannot access `/esg/config/esgf_idp_static.xml': No such file or directory
```

I am not sure if this is an expected error or not.

```
Waiting to see Solr listening on port 8983Still not seeing Solr listening on 8983 after 30 seconds!
 [\]  tail: cannot open `/usr/local/solr/server/logs/solr.log' for reading: No such file or directory
............. Solr process for slave running on port [8983]... 
```

I am following the link (1) to do the installation although it seems that there's an extended one (2) under revision.
(1) https://github.com/ESGF/esgf-installer/wiki/ESGF-Installation-From-scratch
(2) https://github.com/ESGF/esgf.github.io/wiki/ESGFNode|InstallationProcedure

Which one of those two should I use?

I'd like to fix the current errors to see if I can try to install it again. Is the installation being logged somewhere so that I can see what failed? How should I proceed now? Should I uninstall everything and restart from scratch?

Thanks for your help

**Comment by SebastienDenvil** [comment]
You tried to install a full node. This is not recommended for a first try. Please read:
http://esgf.llnl.gov/media/pdf/ESGF-Policies-and-Guidelines-V1.0.pdf

My advise is:

Uninstall first
https://github.com/ESGF/esgf-installer/wiki/ESGF-Full-Uninstall

Then install a data only node. I suggest Installation-Using-Autoinstaller below.
https://github.com/ESGF/esgf-installer/wiki/ESGF-Installation-From-scratch
https://github.com/ESGF/esgf-installer/wiki/ESGF-Installation-Using-Autoinstaller

**Comment by thiasB** [comment]
The current release builds on CoG v3.5.2 which has unresolved dependencies during installation at the moment. I came across this issue yesterday. The trick was to install CoG v3.7 afterwards as Luca suggests anyways.

**Comment by omula** [comment]
Thanks the installer works much better now.
