### ISSUE TITLE
fix myproxy RPM problem

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esgf-installer#161]
Hi,

I was going to do a quick pull request for the following, but the code seems to be different in devel from master, where I had the issue.  Could someone who is familiar with the code in devel check whether this is fixed please?

At line 6823 of `esg-node` in master, is a `yum install` command which includes `myproxy` but not `myproxy-libs`. However, although the dependencies of the `myproxy` RPM include `myproxy-libs`, it  does not require a specific version, even though the correct version is still needed and at run time `myproxy-logon` will abort if the library version is incompatible. Running `yum install myproxy` on a system that has an existing installation of both `myproxy` and `myproxy-libs` may cause only `myproxy` to be updated, leaving `myproxy-libs` at an incompatible older version. The proper fix would be for the RPM packager of myproxy to specify an exact version in the dependency (`Requires: myproxy-libs = %{version}-%{release}` in the spec file), but for us to work around it, we should ensure that any `yum install myproxy` command in the installer explicitly specifies `myproxy-libs` in addition, assuming that the latest versions of each of these in the repository will be compatible with each other.

**Comment by alaniwi** [comment]
Correction: it seems that the dependency on `myproxy-libs` has been lost altogether. This is in `myproxy-6.1.21-2.el6+gt6.x86_64`.

The older version on our system (`6.1.18-1.el6+gt6`) did in fact have an exact version dependency (`myproxy-libs = 6.1.18-1.el6+gt6`), although of course this did not prevent a `yum update myproxy` from updating `myproxy` to 6.1.21 while leaving `myproxy-libs` unchanged.

Before:
```
# rpm -q myproxy
myproxy-6.1.18-1.el6+gt6.x86_64
# rpm -qR myproxy | grep myproxy-libs
myproxy-libs = 6.1.18-1.el6+gt6
#
```

After:
```
# rpm -q myproxy
myproxy-6.1.21-2.el6+gt6.x86_64
# rpm -qR myproxy | grep myproxy-libs
#
```

So essentially, whatever you were doing previously was correct, but needs to be put back again.

**Comment by alaniwi** [comment]
Actually, seems that the problem is that the RPM dependency has been lost entirely (at 6.1.21), and was previously an exact version dependency (at 6.1.18). In any case, the workaround is still the same: install both explicitly.

**Comment by pchengi** [comment]
Alan, I don't think you should be doing a myproxy installation using yum, at least prior to setting up the custom repo. The entry in line 6128 that you mention was removed because it was picking up the myproxy from epel, which is not compliant with our needs. Check the lines in esg-globus for details. Pasting an extract here:

  # Setup Globus RPM repo
    wget -O globus-connect-server-repo-latest.noarch.rpm http://toolkit.globus.org/ftppub/globus-connect-server/globus-connect-server-repo-latest.noarch.rpm
    [ $? != 0 ] && echo "ERROR: Could not download the Globus Repo RPM" && popd && checked_done 1
    rpm --import http://www.globus.org/ftppub/globus-connect-server/RPM-GPG-KEY-Globus
    [ $? != 0 ] && echo "ERROR: Could not download the Globus Repo GPG Key" && popd && checked_done 1
    rpm -i globus-connect-server-repo-latest.noarch.rpm

    # Install Globus and ESGF RPMs
    yum -y install ${config_type}
    yum -y update ${config_type}
    if [ ${config_type} = 'globus-connect-server-io' ]; then
        yum -y install globus-authz-esgsaml-callout globus-gaa globus-adq customgsiauthzinterface
        yum -y update globus-authz-esgsaml-callout globus-gaa globus-adq customgsiauthzinterface
    else
        yum -y install mhash pam-pgsql
        yum -y update mhash pam-pgsql
    fi

**Comment by alaniwi** [comment]
Prashanth,

We have to be able to cope with systems that *have* had myproxy already installed with yum before esg-node is installed.  Bear in mind, the package list in the initial operating system installation may be controlled by a general IT administrator who builds the machine rather than by the ESG data node admin who does the esg-node installation.  I installed v2.3.8-master on such a node, and had this exact problem.  Unless these changes in devel are going to be merged into master very soon, then at least for the time being we need to change the line that I refer to in master, so as to add myproxy-libs as suggested.  It can certainly do no harm.  Please can you reopen this ticket until that is done.

Thanks,
Alan

**Comment by alaniwi** [comment]
I am going to send a pull request against master.

**Comment by alaniwi** [comment]
Oh okay, you have already merged into master?

**Comment by alaniwi** [comment]
Ah, no you haven't, just the line number had changed. Please see https://github.com/ESGF/esgf-installer/pull/162

**Comment by pchengi** [comment]
Alan, the solution is to remove myproxy from the line and NOT to add myproxy-libs, at least as per @lukaszlacinski . v2.4 is already delayed, and I just determined that removing the myproxy from the yum list does the trick, on clean machines.  At any rate, if adding myproxy-libs solves your problem, you can by all means do a yum install prior to the esg-node install, as the esgf installer doesn't uninstall myproxy before proceeding.
