### ISSUE TITLE
Missing esgscan_directory script in cdat home directory

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#167]
The test_esgcet() function attempts to invoke called esgscan_directory from the cdat home directory (aka /usr/local/uvcdat/2.2.0).  The esgscan_directory script from the publisher is not that directory from installs that I have run to completion.

One installation that I completed on a VM has the script located at /usr/local/src/esgf/workbench/esg/esg-publisher/src/python/esgcet/scripts.  

Either the test function should be updated or the script should be included in the cdat home directory along with the other publisher scripts.

**Comment by sashakames** [comment]
Deprecated for esgprep
