### ISSUE TITLE
Cannot download pip

### ISSUE THREAD

**Issue by omula** [ESGF/esgf-installer#169]
While trying to install esgf using esg-node Version: v2.4.24-master-release it fails to download pip. Script continues installation.

ORGDIR was /usr/local/src/esgf/workbench/esg/apache_frontend/apache-frontend
pip not found at NA. Will now custom-install
--2017-03-28 12:42:28--  https://bootstrap.pypa.io/get_pip.py
Resolving bootstrap.pypa.io... 151.101.132.175
Connecting to bootstrap.pypa.io|151.101.132.175|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-28 12:42:28 ERROR 404: Not Found.

The right script name to download is get-pip.py.

**Comment by sashakames** [comment]
this is in apache_frontend and has been corrected.  Thanks for the feedback.
