### ISSUE TITLE
--verify not working

### ISSUE THREAD

**Issue by omula** [ESGF/esgf-installer#170]
Cannot verify ESGF installation as the verify doesnt' work.

```
INFO       2017-03-28 18:22:17,920 Upgrading schema to latest version. (This may take a while.)
INFO       2017-03-28 18:22:17,940 Initializing standard names ...
INFO       2017-03-28 18:22:20,748 Initializing projects, models, and experiments ...
/usr/local/uvcdat/2.2.0/bin/esgscan_directory --dataset pcmdi...test.mytest --project test /esg/data/test > mytest.txt
/usr/local/bin/esg-node: line 1217: /usr/local/uvcdat/2.2.0/bin/esgscan_directory: No such file or directory
 ERROR: ESG directory scan failed
/usr/local/bin
```

esgscan_directory doesn't seem to be available in uvcdat package

[root@esgf-dev bin]# rpm -ql uvcdat-2.2.0-1.x86_64|grep -i esgscan
[root@esgf-dev bin]# 
 
Tested with:
[root@esgf-dev bin]# ./esg-node -v
Version: v2.4.24-master-release
Release: Bifrost
Earth Systems Grid Federation (http://esgf.llnl.gov)
ESGF Node Installation Script

**Comment by sashakames** [comment]
>> esgscan_directory doesn't seem to be available in uvcdat package

That command has been deprecated and replaced by "esgprep"  Please see the esgpublisher documentation here:   http://esgf.github.io/esg-publisher/index.html
In esgf 2.5 we are adding an new automated test for publication.  Not sure about the future support for --verify
