### ISSUE TITLE
esg.env still needed?

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-installer#174]
I spend way too much time trying to add an entry to this file.   I'm wondering in what cases its still needed and if the one-size-fits-all approach is still viable.  If we can say no and no, then would be great to just drop from the migration of the installer / esg-node to python.

**Comment by sashakames** [comment]
I don't see much traction on this for 2.X releases

**Comment by William-Hill** [comment]
Removed references to esg.env in 3.0 development d5318cedddccf92b0d298639b0d6d5eae9a3d7ed

**Comment by sashakames** [comment]
Fine by me to close this.  Trusting that modules will run correctly ie., whatever needed environments get contributed

**Comment by alaniwi** [comment]
Please see my comments at #290. Thanks.
