### ISSUE TITLE
automate "self-signed" keypair installation

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-installer#175]
Only do this for test installations, e.g. with a --test option.  This would facilitate automated testing.  For production installations with trusted certs, still necessary to go through manual installation process.

**Comment by William-Hill** [comment]
@sashakames Is this referring to installing the keypair for Apache?  Or for Tomcat?

**Comment by sashakames** [comment]
The current --install-keypair in bash does both, as in no assumption that a keypair is set in /etc/certs nor tomcat.  I have a working expect script that handles the bash case, but if the 3.0 version doesn't have the same command-line invocation, followed by interaction, that script wouldn't work.

**Comment by William-Hill** [comment]
I can make the command line invocation.  I think I'm getting confused with all of the key and cert management.  I'm still going to have the conversation with Lukasz to get some clarity.  I have most of the key/cert management functions ported to Python and individually tested.  Now I'm just trying to understand how to piece everything together.

**Comment by sashakames** [comment]
I'm wondering if are better off revamping the command-line.  Is there really a need for all the questions?  could the CA cert be speficied on the command line?  should we have --cert --key and --ca ?  how about reading the password from /esg/config/.esg_pass ?  Just brainstorming here....

**Comment by William-Hill** [comment]
Yeah I think some of the questions can be skipped or answered in a file similar to Zed's autoinstaller.  That way a typo at the command line doesn't ruin an entire installation.  I was thinking of using /esg/config/esgf.properties for that purpose.  It could be manually edited or populated from a command line question using Python's ConfigParser module.

**Comment by William-Hill** [comment]
I have automated most of this, but when running the installation and trying to access one of the webapp urls (testing with Thredds currently), the browser blocks me due to using a self-signed cert.  This didn't seem to happen in the past so I may be missing something.

**Comment by sashakames** [comment]
(1) we might be able to adjust the self-signed certs so browsers allow for exceptions (2) find way to import the CA root for testing purposes.  (3) don't bother to test with a browser at all and just use automated calls (curl, wget, requests, etc)

**Comment by William-Hill** [comment]
Code is converted and merged into python_devel
