### ISSUE TITLE
prompt before unpublish in `esgtest_publish`

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esgf-installer#198]
It is helpful to be able to test interactively whether the test dataset has been correctly published, before it gets unpublished. Currently, it will publish the test dataset and then without any further prompting it will unpublish again.

Please can `esgftest_publish` be changed to add some kind of "do you want to unpublish?" prompt. Then the user will have the option to answer no, or at least to delay before answering yes.

**Comment by sashakames** [comment]
esgtest_publish is part of the esg-publisher repo - better to move this there so we can appropriately track
