### ISSUE TITLE
Update esg_init when running build scripts

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#201]
Currently, the esg-init file must be updated manually when completing a build with new version numbers.

The build script should edit the esg-init file to update with new version numbers that are found from git describe

**Comment by pchengi** [comment]
@William-Hill , this is NOT to be done. Developers often tag their repos, and the latest tag is not necessarily the one to be pulled into the release. The release manager confirms this now, prior to cutting a release. Automating this might lead to unwanted results.
