### ISSUE TITLE
Compute configuration fails with "Argument too long" bash error

### ISSUE THREAD

**Issue by stephenpascoe** [ESGF/esgf-installer#21]
This issue has occured on data/compute and idp/index/data/compute nodes from scratch installations. Rerun the installation again doest not solve the problem. The only woraround I found is to remove /usr/local/ferret and rerun the installation. 

```
*******************************
Setting up LAS Product Server...
*******************************

Getting LAS...
Don't see LAS tar file las-esgf-v8.1.tar.gz Downloading LAS from las-esgf-v8.1.tar.gz -to-> /usr/local/src/esgf/workbench/esg/ferret/8.1/las-esgf-v8.1.tar.gz
wget -O 'las-esgf-v8.1.tar.gz' 'ftp://ftp.pmel.noaa.gov/pub/las/las-esgf-v8.1.tar.gz'
/usr/local/bin/esg-product-server: line 426: /usr/bin/wget: Argument list too long
 ERROR: Could not download LAS:las-esgf-v8.1.tar.gz
```

This would appear to be a low-level bash bug (because the command being executed definitely only has 3 arguments).
One possible work-around would be to try to increase ulimit -s. it is 10240 by default. On Linux, the maximum amount of space for command arguments is 1/4th of the amount of available stack space.

**Comment by ncaripsl** [comment]
fixed in 1.8.0, LAS component subscript is not being sourced anymore
