### ISSUE TITLE
AUTHSERVICE points to wrong URL

### ISSUE THREAD

**Issue by lukaszlacinski** [ESGF/esgf-installer#214]
GridFTP authorization callout gets a URL to the authorization service from /etc/grid-security/esgsaml_auth.conf that points to the IdP node instead of the data node. Alan created the pull request with a fix, https://github.com/ESGF/esgf-installer/pull/145/files. Reopening the pull request and merging with the devel branch should fix the issue.

**Comment by William-Hill** [comment]
@lukaszlacinski Is this something that needs to be fixed in version 2.5?  Also, I tried to reopen the pull request and it says the repo that the pull request originated from has been deleted so I can't reopen it.  We can make the change manually if need be.

**Comment by lukaszlacinski** [comment]
@William-Hill I am going to create a new pull request based on Alan's fix.

**Comment by lukaszlacinski** [comment]
I created a new corresponding pull request, https://github.com/ESGF/esgf-installer/pull/223.
