### ISSUE TITLE
esgcet / thredds detection

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-installer#225]
Properly detect the esg-publisher (esgcet) version
Conda info or pip freeze should work

not how to detect the correct thredds version unless we manage internally and try to keep consistent (might be better for next-gen installer)

**Comment by William-Hill** [comment]
Spoke with Sean (Thredds maintainer) and he said that the Thredds version is maintained in the META-INF/MANIFEST.MF file.  It lists the major version but not sure how consistent the subversion tracking is.

**Comment by William-Hill** [comment]
Used pip freeze to detect esgcet version in 01678179957db85602a6da8c66bc110d073dd2d7

**Comment by William-Hill** [comment]
Parsed the MANIFEST.MF file for the Thredds version aab5fc7eea7f8ffe176473b149a77c1eccba050d
