### ISSUE TITLE
Use new esg-search release v4.13.6

### ISSUE THREAD

**Issue by LucaCinquini** [ESGF/esgf-installer#243]
Alan has found a bug in how the esg-search converts longitudes to the proper range, in some data limit cases, and he contributed code to fix it. Please use the newest esg-search release tagged v4.13.5

**Comment by LucaCinquini** [comment]
Actually make that v4.13.6

**Comment by William-Hill** [comment]
We just got the latest master release out today and I didn't see this until after we had already started the upgrade.  I can do a minor release to roll this in next week.
