### ISSUE TITLE
Java updates for upgrading [2.5.13]

### ISSUE THREAD

**Issue by kailu-nsc** [ESGF/esgf-installer#247]
During the upgrading from 2.4.24-master to 2.5.13-master, Java is still version jdk1.8.0_131 and has not been updated to recent version (e.g. jdk1.8.0_141 or 144).

**Comment by William-Hill** [comment]
@kailu-nsc This is something that I can bring up at tomorrow morning's IWT Telco as far as if we need to stay on the cutting edge of Java releases

**Comment by kailu-nsc** [comment]
The Java version jdk1.8.0_141 includes some critical security updates.
http://www.oracle.com/technetwork/security-advisory/cpujul2017-3236622.html#AppendixJAVA

**Comment by William-Hill** [comment]
Updated Java to jdk1.8.0_144 on mirror.  Testing pending.
