### ISSUE TITLE
version of software to be installed

### ISSUE THREAD

**Issue by gardoll** [ESGF/esgf-installer#250]
During the installation or the upgrade process, it is asked to install or upgrade some software but without the version number. Sometime the required version is displayed, sometime not, but the version of the software to be installed or upgraded is not displayed for:

- threeds
- esgcet
- openid relying party
- globus myproxy
- globus gridftp

This is quite odd from the node administrator point of view: the upgrade process asks you to install a software that is detected without knowing which version number will be installed/upgraded to.

**Comment by pchengi** [comment]
Relevant versions now echoed during upgrade.

**Comment by gardoll** [comment]
please add the commit hash as comment when closing the issue. It will improve traceability. :)
