### ISSUE TITLE
Better mirror support

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-installer#254]
AIMS1 should be equal primary mirror.  Sites should be able to bind to a regular mirror for non-install fetches, (but do sync check if not a primary).  Override with alternate or local filesystem mirror instead of always fetch for test deployments.

**Comment by pchengi** [comment]
You are either referring to
1. The coffee mirror checking AIMS1 for changes, and updating itself. (Bi-directional rsync)
2. Installation scripts using the primary mirror.

#1 is not possible, as updates MUST be unidirectional. Consider the following case:
If certain unnecessary files on coffee are deleted as part of a cleanup exercise, and that has not been updated yet on AIMS2, and the coffee server runs a check on the files on AIMS1 to sync up, it'll find the files locally deleted, on AIMS1, and bring them in, undoing the cleanup work. RSYNCs should always be unidirectional, if performed automatically. 

2 This is fundamentally not feasible. All mirrors are considered to be equally useable, and the fastest mirror is supplied. Having a primary mirror is to simply guard against mirrors being out of sync. If currently, the fastest mirror is found to be out of sync with the primary, the installer falls back to the primary. If you have more than one 'equal primary' mirror, and for whatever reason, the two (or more equal primary mirrors aren't in perfect sync), it's not possible for an automated script to decide which mirror to use. The only acceptable solution in such a scenario is to terminate without using any mirror, resulting in denial of service.

**Comment by sashakames** [comment]
1.  You are correct.  the master mirror can only receive pushes, but cannot pull.  We would push from aims1  and pull (disable our rsync pull during that period);  that is a build script issue.
2. I am advocating an overhaul to the method for mirror determination for v3.0 - the current approach is too inefficient when confronted with periods of high network latencies.  We could still have a single primary as an ultimate fallback.

**Comment by pchengi** [comment]
The 2.6 release brings in --use-local-mirror option; in addition to this, I'm making a change to the esgf-build scripts, that'll push out bootstrap files with aims and liu urls, as the files fetched by the bootstrap are the only ones which are currently only from coffee.
