### ISSUE TITLE
missing cmip6 conf in esg-autoinstall

### ISSUE THREAD

**Issue by gardoll** [ESGF/esgf-installer#257]
CMIP6 installation in esg-autoinstall is missing.

**Comment by sashakames** [comment]
@gardoll Can you provide a more specific suggestion for the solution here?

**Comment by sashakames** [comment]
The main issue is CMOR support, which we didn't want optional, but because most of the active node administrators would want this, the autoinstaller does default this.  Its also fairly straightforward to change the expect script if needed.  Next release.
