### ISSUE TITLE
remove the -Xss2m flag in esg-functions

### ISSUE THREAD

**Issue by gardoll** [ESGF/esgf-installer#259]
-Xss2m flag must be removed since it causes some trouble (depending of the wpu load) and with the last kernel (2.6.32-696.6.3.el6.x86_64), the tomcat bug doesn't occur anymore (the bug concerns only the version 2.6.32-696.3.2.el6.x86_64).

**Comment by sashakames** [comment]
Should have done a while a go.  now in devel branch,  should tag issue with next release vTBD
