### ISSUE TITLE
Move tests to separate directory

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#260]
The tests currently live in the same directory as the source files.  They should be moved to their own directory.  Can be run using test discovery.

**Comment by sashakames** [comment]
We're seeing issues lately where CI would help with the 2.X version.  However, given the overall lousiness of the "bash installer" I don't think its a great use of time, if 3.0 will be ready, to implement for 2.X if that is considerable extra effort.  OTOH it might be worth it to detect some of the issues found recently with esgf-security and esg-orp

**Comment by William-Hill** [comment]
Try to replicate testing folder directory of the VCS (https://github.com/UV-CDAT/vcs) project.

**Comment by William-Hill** [comment]
Completed in python_devel branch
