### ISSUE TITLE
Make Conda installation step 0 for ESGF 3.0

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#263]
Write a script and documentation for installing Conda before running the ESGF Installer.

The script should install conda and create an environment with Python 2.7. 
The user will then have to activate the environment before running the install script.

**Comment by sashakames** [comment]
Conda should update itself periodically too (probably not worth it in 2.X, but perhaps if it lingers too long)

**Comment by William-Hill** [comment]
See README
