### ISSUE TITLE
Upgrade LAS to 8.6.3

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#265]
A security vulnerability was discovered in LAS 8.6.2.  A new point release (2.5.14) will be created to include the updated LAS war (8.6.3) that fixes the vulnerability.

**Comment by attritionorg** [comment]
@William-Hill Do you have a reference for the LAS issue? Not finding anything relevant on Google.

**Comment by William-Hill** [comment]
@attritionorg  It was an issue with Apache Struts.  The message from Roland (maintainer of LAS is below):

"Apache has released a new version of Struts 2. LAS was not (as far as I can tell) affected by any vulnerabilities discovered between 2.5.12 and 2.5.13, but to keep in step with Struts 2 and to
avoid any issues if security teams would like to have applications at the latest version, I have made a new release of LAS which upgrades to Struts 2.5.13."

**Comment by William-Hill** [comment]
Updated LAS on mirror to 8.6.3.  Testing pending.
