### ISSUE TITLE
inaccurate messages

### ISSUE THREAD

**Issue by gardoll** [ESGF/esgf-installer#271]
I think these messages are inaccurate. Can some give me information about them and eventually modify the questions.

- What is the default peer to this node?
==> What is the nature of the relation ? What for ? What do I suppose to answer when I install the stack on a data node ? same question on a all node ?

- What is the hostname of the node do you plan to publish to?
==> Is it where we want to index data so the index node or where we want to perform the publishing procedure, so the data node ?

**Comment by sashakames** [comment]
(1) Default peer is no longer used;  should be removed.
(2) This is the Index node, but agreed its ambiguous to a new administrator

**Comment by alaniwi** [comment]
I have fixed the above issue (see pull request) but I would still like to know what the "peer group" actually does. I always set it to "esgf-prod" on production nodes and "esgf-test" on test nodes, but how does the software actually use it please?

**Comment by sashakames** [comment]
1) The node manager uses the peer group to fetch the list of "tier-1" aka super-nodes - these lists are different for test vs production federation.
2) we also have the functionality to have separated CA truststores.  The idea being the ESGF-managed root CAs could be different for each test vs production federations.  The peer group makes this determination.   While the functionality is there in the esg-* scripts, we haven't yet set up alternate CAs for the test-fed (still using production).
