### ISSUE TITLE
Error during Python venv installation

### ISSUE THREAD

**Issue by LucaCinquini** [ESGF/esgf-installer#277]
While installing 2.5.14, the following error appeared, although the installer did not stop and eventually completed.

HTTP request sent, awaiting response... 200 OK
Length: 1595408 (1.5M) [text/x-python]
Saving to: `get-pip.py'

100%[================================================================================================>] 1,595,408   --.-K/s   in 0.09s   

2017-10-04 01:30:40 (17.8 MB/s) - `get-pip.py' saved [1595408/1595408]

Requirement already up-to-date: pip in /opt/esgf/python/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg
Requirement already satisfied: virtualenv in /opt/esgf/python/lib/python2.7/site-packages
Already using interpreter /opt/esgf/python/bin/python2.7
New python executable in /opt/esgf/virtual/python/bin/python2.7
Traceback (most recent call last):
  File "/opt/esgf/python/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/opt/esgf/python/lib/python2.7/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/opt/esgf/python/lib/python2.7/site-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/opt/esgf/python/lib/python2.7/site-packages/virtualenv.py", line 1231, in install_python
    shutil.copyfile(executable, py_executable)
  File "/opt/esgf/python/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 26] Text file busy: '/opt/esgf/virtual/python/bin/python2.7'
Requirement already satisfied: flask in /opt/esgf/python/lib/python2.7/site-packages
Requirement already satisfied: itsdangerous>=0.21 in /opt/esgf/python/lib/python2.7/site-packages (from flask)
Requirement already satisfied: click>=2.0 in /opt/esgf/python/lib/python2.7/site-packages (from flask)

**Comment by alaniwi** [comment]
Seems that `Text file busy` means an attempt to write to an executable while another process is running it.

**Comment by alaniwi** [comment]
Example:
```
bash-4.2$ cp /bin/sleep .
bash-4.2$ ./sleep 100 &
[1] 7866
bash-4.2$ cat >> sleep
bash: sleep: Text file busy
```

So seems it is trying to overwrite `py_executable` while something is already using it.

**Comment by alaniwi** [comment]
It might be useful to insert 
```
fuser -v /opt/esgf/virtual/python/bin/python2.7
```
before the `pip` command, to see which process is using it.

**Comment by sashakames** [comment]
Didn't reproduce this.  Was this an install from scratch?

**Comment by LucaCinquini** [comment]
No, it was an upgrade from 2.5.13.
