### ISSUE TITLE
Supernodes error while installing 2.5.14

### ISSUE THREAD

**Issue by LucaCinquini** [ESGF/esgf-installer#278]
While installing 2.5.14, the following error appeared during the node manager installation. Eventually the script kept going and completed.

--2017-10-04 01:32:41--  http://aims1.llnl.gov/nm-cfg/esgf-test/esgf_supernodes_list.json
Resolving aims1.llnl.gov... 198.128.245.180
Connecting to aims1.llnl.gov|198.128.245.180|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 111 [application/json]
Saving to: `/esg/config/esgf_supernodes_list.json'

100%[================================================================================================>] 111         --.-K/s   in 0s      

2017-10-04 01:32:41 (11.4 MB/s) - `/esg/config/esgf_supernodes_list.json' saved [111/111]

/usr/local/esgf-node-manager/src/python/server /usr/local/src/esgf/workbench/esg /usr/local/src/esgf/workbench/esg /usr/local/src/esgf/workbench/esg /usr/local/src/esgf/workbench/esg/apache_frontend/apache-frontend
python gen_nodemap.py esgf-dev.jpl.nasa.gov
running as ['esgf-dev.jpl.nasa.gov']
/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
An Error occurred: No JSON object could be decoded
An Error occurred: HTTPSConnectionPool(host='esgf-index-fedcheck.ceda.ac.uk', port=443): Max retries exceeded with url: /esgf-nm/api?action=sync_node_map_file (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4264d8ffd0>: Failed to establish a new connection: [Errno 110] Connection timed out',))
/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Nodemap retrieval succeeded! exiting...
Automatic peer with super-node (if you administer one, ensure that it is running) [Y/n] 
python ../client/member_node_cmd.py add default 0
/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

**Comment by sashakames** [comment]
the command  python gen_nodemap.py esgf-dev.jpl.nasa.gov 
causes a fetch from other nodes.  The error is likely due to one of the listed nodes not working. But looks like it later succeeded after finding another working source
