### ISSUE TITLE
Dashboard does not install

### ISSUE THREAD

**Issue by LucaCinquini** [ESGF/esgf-installer#279]
I tried the latest installation of 2.5.14 on the JPL production data node. I first removed the directory /usr/local/esgf-dashboard-ip, then run the installer (I tried both the --upgrade and --install options).
The dashboard did not get installed, despite this message on the screen:

-------------------------------
LOADING installer for dashboard... 
 ==> ./esg-dashboard is up to date
export PATH=/usr/local/geoip/bin:/usr/local/esgf-dashboard-ip/bin:/usr/local/openssl/bin:/bin:/usr/local/java/bin:/usr/local/ant/bin:/usr/local/conda/bin:/usr/local/conda/Externals/bin:/usr/local/tomcat/bin:/usr/local/globus/bin:/usr/local/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/conda/envs/esgf-pub/bin:/usr/local/uvcdat/2.2.0/bin:/usr/local/uvcdat/2.2.0/Externals/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/geoip/lib:/var/lib/pgsql/lib:/usr/local/openssl/lib:/usr/local/conda/Externals/lib:/usr/local/globus/lib:/usr/lib64:/usr/lib::$LD_LIBRARY_PATH
 Hmmm... Could not find local file esgf-stats-api.war
Fetching file from http://aims1.llnl.gov/esgf/dist/esgf-stats-api/esgf-stats-api.war -to-> esgf-stats-api.war
--2017-10-04 05:05:04--  http://aims1.llnl.gov/esgf/dist/esgf-stats-api/esgf-stats-api.war
Resolving aims1.llnl.gov... 198.128.245.180
Connecting to aims1.llnl.gov|198.128.245.180|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8248932 (7.9M)
Saving to: `esgf-stats-api.war'

100%[==================================================================================================================================================>] 8,248,932    410K/s   in 20s

**Comment by sashakames** [comment]
Didn't reproduce
