### ISSUE TITLE
[2.5.14] SLCS crash

### ISSUE THREAD

**Issue by LucaCinquini** [ESGF/esgf-installer#280]
After a fresh install of 2.5.14 on the dev site at JPL, the SLCS server generates a 500 error at the time of logging in to the admin interface. The stack trace in the apache log is as follows:

[Wed Oct 04 05:52:55 2017] [error] [client 128.149.81.154] client denied by server configuration: /usr/local/cog/cog_install/apache/wsgi.py
[Wed Oct 04 05:52:56 2017] [error] [client 128.149.81.154] client denied by server configuration: /usr/local/cog/cog_install/apache/wsgi.py
[Wed Oct 04 06:52:56 2017] [error] [client 128.149.81.154] WARNING:django.request:Not Found: /favicon.ico
[Wed Oct 04 05:53:05 2017] [error] [client 128.149.81.154] client denied by server configuration: /usr/local/cog/cog_install/apache/wsgi.py, referer: https://esgf-dev.jpl.nasa.gov/esgf-slcs/admin/login/?next=/esgf-slcs/admin/
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154] [ERROR] [2017-10-04 12:53:05,227] [django.request:284] [Dummy-1] Internal Server Error: /esgf-slcs/admin/login/
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154] Traceback (most recent call last):
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]   File "/usr/local/esgf-slcs-server/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]     response = self.process_exception_by_middleware(e, request)
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]   File "/usr/local/esgf-slcs-server/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]   File "/usr/local/esgf-slcs-server/venv/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]     response = view_func(request, *args, **kwargs)
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]   File "/usr/local/esgf-slcs-server/venv/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 414, in login
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]     return login(request, **defaults)
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]   File "/usr/local/esgf-slcs-server/venv/lib/python2.7/site-packages/django/contrib/auth/views.py", line 49, in inner
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]     return func(*args, **kwargs)
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]   File "/usr/local/esgf-slcs-server/venv/lib/python2.7/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]     return view(request, *args, **kwargs)
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]   File "/usr/local/esgf-slcs-server/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]     response = view_func(request, *args, **kwargs)
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]   File "/usr/local/esgf-slcs-server/venv/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]     response = view_func(request, *args, **kwargs)
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]   File "/usr/local/esgf-slcs-server/venv/lib/python2.7/site-packages/django/contrib/auth/views.py", line 69, in login
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]     if form.is_valid():
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]   File "/usr/local/esgf-slcs-server/venv/lib/python2.7/site-packages/django/forms/forms.py", line 161, in is_valid
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]     return self.is_bound and not self.errors
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]   File "/usr/local/esgf-slcs-server/venv/lib/python2.7/site-packages/django/forms/forms.py", line 153, in errors
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]     self.full_clean()
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]   File "/usr/local/esgf-slcs-server/venv/lib/python2.7/site-packages/django/forms/forms.py", line 363, in full_clean
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]     self._clean_form()
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]   File "/usr/local/esgf-slcs-server/venv/lib/python2.7/site-packages/django/forms/forms.py", line 390, in _clean_form
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]     cleaned_data = self.clean()
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]   File "/usr/local/esgf-slcs-server/venv/lib/python2.7/site-packages/django/contrib/auth/forms.py", line 161, in clean
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]     password=password)
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]   File "/usr/local/esgf-slcs-server/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 74, in authenticate
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]     user = backend.authenticate(**credentials)
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]   File "/data/local/esgf-slcs-server/src/esgf_slcs_server/esgf_auth/backend.py", line 34, in authenticate
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]     .format(sql.Identifier(settings.ESGF_USERDB_USER_SCHEMA),
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]   File "/usr/local/esgf-slcs-server/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154]     return getattr(self._wrapped, name)
[Wed Oct 04 12:53:05 2017] [error] [client 128.149.81.154] AttributeError: 'Settings' object has no attribute 'ESGF_USERDB_USER_SCHEMA'

**Comment by LucaCinquini** [comment]
I would like to add that if you open the file:

/usr/local/esgf-slcs-server/src/esgf_slcs_server/esgf_slcs_server/settings.py

the field 'ESGF_USERDB_USER_SCHEMA' is nowhere to be found.

**Comment by sashakames** [comment]
My thought is that it was pulling from the devel branch playbook which happened to be missing those settings.  This has been corrected, but need to check a deployment with SLCS

**Comment by sashakames** [comment]
There was a typo on top of that.  Fixed!
