### ISSUE TITLE
Create a virtual env for ESGF 3.0

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#285]
The installation of mod_wsgi for use with apache needs a Python interpreter with shared libraries included.  A virtual env should be created to run the setup in.

**Comment by sashakames** [comment]
Can we find a conda solution for this?  Would installing full-on anaconda from Miniconda help?

**Comment by William-Hill** [comment]
Using a Bash script to install Miniconda and set up a conda environment called esgf-pub
