### ISSUE TITLE
start and stop individual services

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esgf-installer#288]
@William-Hill If you have not already done so, when converting the scripts to python please can you provide a command-line interface to start and stop individual services without doing a full esg-node restart.

Currently with the shell scripts this is possible for services that have an init script (apache, postgres) but more tricky for Solr / tomcat -- functions exist to start and stop them but are difficult to use from the command line because they require various shell variables to be set before calling.  It would be a good improvement if the python scripts let you do this.

Thanks.

**Comment by sashakames** [comment]
+1

**Comment by LucaCinquini** [comment]
Docker will use "supervisor" to execute just this. Supervisor is written in Python, and it could be installed on each node by the Python installer. It works really well.

**Comment by William-Hill** [comment]
@alaniwi I've already added that functionality for Apache and Postgres but it's a great idea to do it for the other components as well.  I haven't gotten to a Solr setup yet but I'll add start/stop functionality for Tomcat this week.

**Comment by William-Hill** [comment]
Added Tomcat management functions 3378ac6277b5a5a6bf4b3da60601ead5b25f83d7

**Comment by William-Hill** [comment]
Individual start and stop methods are implemented for the various modules in the python_devel branch
