### ISSUE TITLE
Post all dependencies for TDS filters

### ISSUE THREAD

**Issue by LucaCinquini** [ESGF/esgf-installer#293]
I am trying to clean up how the Docker image for the data node is built, and I stumbled upon this fact. Right now, the jar files that are needed by the TDS access control filters are copied from several locations, including the expanded distribution of the esg-orp and old node-manager (both of which are going to disappear). I would like to suggest that all necessary jars come from a single location, accessible from the web.

We already have some of these jars in the directory:

https://aims1.llnl.gov/esgf/dist/filters/

I would recommend adding the other needed jars in the same place, specifically these jars are missing:

xmlsec-1.4.2.jar
velocity-1.5.jar
serializer-2.9.1.jar
postgresql-8.4-703.jdbc3.jar
xalan-2.7.2.jar
xercesImpl-2.10.0.jar 
xml-apis-1.4.01.jar
commons-io-2.4.jar
commons-dbcp-1.4.jar
commons-dbutils-1.3.jar 
commons-pool-1.5.4.jar

**Comment by sashakames** [comment]
We are still using distrib-coffee for the master mirror, so I guess just a matter of pushing the jars there.

**Comment by sashakames** [comment]
Pushed to the mirrors.
@LucaCinquini Can you test?

**Comment by pchengi** [comment]
The jars on the distrib server are practically invisible, and pose a security hazard if they are not really updated during an esgf-build execution. I've moved some of them to this repo now, and we can remove/replace them as needed. We should periodically audit them for security.
https://github.com/ESGF/dep-filters
