### ISSUE TITLE
implement routine testing of Solr replica shards

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esgf-installer#304]
_[Not directly related to the installer - feel free to move this ticket elsewhere as required.]_

We need to implement automated testing to search for datasets from each master index in the federation via each search site, in order to identify any cases where indexes are missing from the search configuration at remote sites.

I envisage that it would produce a 2-d matrix of results, that could be presented as an HTML table.

**Comment by sashakames** [comment]
Looks like Lukasz's monitoring is accomplishing this:

https://esgf.anl.gov/monitor/

**Comment by pchengi** [comment]
Also being monitored here, @alaniwi 
https://esg-dn1.nsc.liu.se/api/nodealerts
