### ISSUE TITLE
more robust handling of version checking for installed version of postgres

### ISSUE THREAD

**Issue by pchengi** [ESGF/esgf-installer#308]
Failure observed on machine running postgresql 8.4.20

Line 50, in parse
    raise ValueError('%s is not valid SemVer string' % version)
ValueError: editing
 is not valid SemVer string
(esgf-pub) [root@esg-idx installer]# psql --version
psql (PostgreSQL) 8.4.20
contains support for command-line editing

**Comment by William-Hill** [comment]
Fixed with 8e33319f1be8b9c9650ec01e1322842157cf11fa
