### ISSUE TITLE
Typo in esgf-httpd.conf redirect on esgf-node

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#321]
There a redirect from pcmdi9 to esgf-node.llnl.gov in the esgf-httpd.conf (line 155).

pcmdi9.llnl.gov is misspelled as "pcmid9.llnl.gov"

**Comment by sashakames** [comment]
That is a LLNL specific config that shouldn't be in the general file.  Does this belong in the installer or is it an apache_frontend issue?

**Comment by sashakames** [comment]
This appears to be an LLNL-specific setting that got propagated elsewhere.  Need to find where the file is sourced from, as not clear where the offending setting actually originates.  Not an issue in apache-frontend, as the template is correct.

**Comment by pchengi** [comment]
Since this isn't related to apache-frontend or the installer itself, I'm closing this.
