### ISSUE TITLE
make CA generation depend on whether IDP (rather than index) is enabled

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esgf-installer#326]
In the existing `generate_esgf_csrs` and `install_local_certs` functions in `esg-node`, the logic to decide whether to create a local CA certificate depends on whether the `INDEX_BIT` is set in the node type selection. However, the purpose of the CA is to sign myproxy certificates, which is associated with the IDP rather than index component. So this test ought to be changed, if not in 2.x then at least in the equivalent script for 3.0.

**Comment by pchengi** [comment]
Thanks for this.
Fixed in commit f2deed1df93bfde86b9b39cc84f68272e5abc4c3.
