### ISSUE TITLE
Upgrade slave Solr to port 80

### ISSUE THREAD

**Issue by LucaCinquini** [ESGF/esgf-installer#33]

**Comment by ncaripsl** [comment]
Hi Luca, is this still planned?

**Comment by LucaCinquini** [comment]
Hi Nicolas,
yes it must be done - part of a more general Solr upgrade, We’ll tackle it in the next few months.
thanks, Luca

On Mar 6, 2015, at 2:35 AM, Nicolas Carenton <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Luca, is this still planned?

**Comment by pchengi** [comment]
Hi Luca and Nicolas,
This is one of the things I've tried out, after the Apache migration and I have got it to work! What's harder (or impossible) is to get everybody to upgrade at once, so one possible solution is to make the esg-search code to try normal http and failover to 8983, while trying to reach the solr port, as solr can now be reached on both 80 and 8983 ports.

**Comment by pchengi** [comment]
This has been achieved within esgf-httpd.conf (apache-frontend)
