### ISSUE TITLE
esg-purge script should unmount all gridftp mounts

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esgf-installer#332]
It tests for `/esg/gridftp_root/esg_dataroot` but there could be other mount points for other dataset roots.

https://github.com/ESGF/esgf-installer/blob/eb674f1bd5759ce539d60bf0a7f15302999f6ab2/esg-purge.sh#L107-L109

**Comment by pchengi** [comment]
fixed in commit 224d6f100
