### ISSUE TITLE
Broken URL in check_for_group_intersection_with function

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#333]
The check_for_group_intersection_with() function is trying to make a request to the node manager on line 4845:
local target_groups=$(curl -s http://${target_node}/esgf-node-manager/registration.xml | sed  -n 's#.*nodePeerGroup="\([^"]*\)".*hostname="'${target_node}'".*#\1#p')

Replacing target_node with an actual node name results in a 404 in the browser.  The node manager is accessed at /esgf-nm instead of /esgf-node-manager

**Comment by sashakames** [comment]
This function should be deprecated as the node manager is discontinued.

**Comment by pchengi** [comment]
fixed in commit 726ef732aa55faef4c7f9ca5bf6143ef84b5c7c3
