### ISSUE TITLE
Wrong certificate is present despite install

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-installer#335]
Ran esg-node --install keypair,
/etc/certs/hostcert.pem has the correct cert, but that doesn't get seen by browser.  Eg. expected MIIGLjCCBRagA....   found MIIEAjCCAuqgAwIBAgI......

[ames4@esgf-dev1 ~]$ wget -O - --no-check-certificate https://esgf-dev1.llnl.gov/
--2018-02-06 14:50:43--  https://esgf-dev1.llnl.gov/
Resolving esgf-dev1.llnl.gov... 198.128.245.131
Connecting to esgf-dev1.llnl.gov|198.128.245.131|:443... connected.
WARNING: cannot verify esgf-dev1.llnl.gov’s certificate, issued by “/C=--/ST=SomeState/L=SomeCity/O=SomeOrganization/OU=SomeOrganizationalUnit/CN=esgf-dev1.llnl.gov/emailAddress=root@esgf-dev1.llnl.gov”:
  Unable to locally verify the issuer’s authority.
HTTP request sent, awaiting response... 403 Forbidden
2018-02-06 14:50:43 ERROR 403: Forbidden.

This was after an upgrade from 2.5.17 "index data idp" nothing was done manually out of the ordinary

**Comment by pchengi** [comment]
Very strange. Did you see anything in the output, after the install-keypair?  Did you see the stuff you generally see? Or saw anything that you generally don't?

**Comment by sashakames** [comment]
There were far fewer certificates listed in the last phase of install-keypair, otherwise everything else appears as normal.
