### ISSUE TITLE
orp should install under type index

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-installer#346]
The orp is needed for successful publishing to an index.  If a node doesn't have type data, this will fail.  It appears that orp is associated with the data bit, but I recall my index node not having the data bit and it had installed in the past.  I'll provide a PR with updated logic (for devel branch testing toward a 2.6.6 release)

**Comment by LucaCinquini** [comment]
To confirm... it’s  needed for both index and data... it needs to be installed on both..
Thanks, Luca

On Feb 23, 2018, at 11:29 AM, Sasha Ames <notifications@github.com<mailto:notifications@github.com>> wrote:


The orp is needed for successful publishing to an index. If a node doesn't have type data, this will fail. It appears that orp is associated with the data bit, but I recall my index node not having the data bit and it had installed in the past. I'll provide a PR with updated logic (for devel branch testing toward a 2.6.6 release)

**Comment by William-Hill** [comment]
Added for 3.0 with 8e1eb46c69452b1cf7026bc24b664b351746573e

**Comment by pchengi** [comment]
Fixed by @sashakames in commit a7e7adcc3
