### ISSUE TITLE
index node fixes

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-installer#348]
1) update SOLR to 5.5.5
2) update JAVA
3) start slave shard (8983)

**Comment by William-Hill** [comment]
Update Java to version 1.8.0_162

**Comment by William-Hill** [comment]
Start additional Solr shards with 63f9ef7c4681a687fcef62103659de0961a98195

**Comment by William-Hill** [comment]
Updated solr version with b34da298437973b8c249ce813d743b6066d51d39
