### ISSUE TITLE
python esg_node.py --start  doesn't

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-installer#356]
After the VM powered off and back on again.  I run this, but apparently no services are actually started.  Moreover, it would be good to have the service running as done in the previous esg-node start.

(esgf-pub) [root@esgf-dev1 esgf-installer]# python esg_node.py --start
[]
DEBUG - esg_property_manager.py - 29 - get_property - 03/16/2018 09:19:10 AM - could not find property esg.root.id
DEBUG - esg_property_manager.py - 29 - get_property - 03/16/2018 09:19:11 AM - could not find property esg.root.id
INFO - esg_node.py - 232 - init_connection - 03/16/2018 09:19:11 AM - esg-node initializing...
INFO - esg_node.py - 234 - init_connection - 03/16/2018 09:19:11 AM - esgf-dev1.llnl.gov
install_type: master
DEBUG - esg_cli_argument_manager.py - 229 - process_arguments - 03/16/2018 09:19:11 AM - args: Namespace(certhowto=False, customsetup=False, devel=False, fixperms=False, generateesgfcsrs=False, generateesgfcsrsext=False, gettype=False, install=False, installlocalcerts=False, prod=False, recommendedsetup=False, restart=False, settype=None, start=True, status=False, stop=False, type=None, update=False, updateapacheconf=False, updatesubinstaller=None, upgrade=False, uselocalfiles=False, version=False)
DEBUG - esg_cli_argument_manager.py - 233 - process_arguments - 03/16/2018 09:19:11 AM - START SERVICES: []
DEBUG - esg_setup.py - 105 - check_for_my_ip - 03/16/2018 09:19:11 AM - Checking for IP address(es)...
INFO - esg_setup.py - 117 - check_for_my_ip - 03/16/2018 09:19:11 AM - Using IP: 198.128.245.131

**Comment by William-Hill** [comment]
The -start functionality of the CLI hasn't been implemented yet but a start method for most of the individual components has been implemented.  I'll just have to make calls to them in --start

**Comment by William-Hill** [comment]
Resolved with 0430cb4d96705f851c689e2f062625ff2131e011
