### ISSUE TITLE
ESGF 3.0: "python esg_node.py --status" returned error 

### ISSUE THREAD

**Issue by muryanto1** [ESGF/esgf-installer#357]
(esgf-pub) [root@esgf-dev1 esgf-installer]# python esg_node.py --status
[]
DEBUG - esg_property_manager.py - 29 - get_property - 03/16/2018 09:22:37 AM - could not find property esg.root.id
DEBUG - esg_property_manager.py - 29 - get_property - 03/16/2018 09:22:38 AM - could not find property esg.root.id
INFO - esg_node.py - 232 - init_connection - 03/16/2018 09:22:38 AM - esg-node initializing...
INFO - esg_node.py - 234 - init_connection - 03/16/2018 09:22:38 AM - esgf-dev1.llnl.gov
install_type: master
DEBUG - esg_functions.py - 458 - call_subprocess - 03/16/2018 09:22:38 AM - command_string: service postgresql status
DEBUG - esg_functions.py - 472 - call_subprocess - 03/16/2018 09:22:38 AM - command_process_stdout: postmaster dead but pid file exists

DEBUG - esg_functions.py - 473 - call_subprocess - 03/16/2018 09:22:38 AM - command_process_stderr: 
DEBUG - esg_functions.py - 474 - call_subprocess - 03/16/2018 09:22:38 AM - command_process.returncode: 1
Traceback (most recent call last):
  File "esg_node.py", line 504, in <module>
    main(node_type_list)
  File "esg_node.py", line 407, in main
    cli_info = esg_cli_argument_manager.process_arguments(node_type_list, devel, esg_dist_url)
  File "/root/esgf-installer/esgf_utilities/esg_cli_argument_manager.py", line 256, in process_arguments
    get_node_status()
  File "/root/esgf-installer/esgf_utilities/esg_cli_argument_manager.py", line 51, in get_node_status
    postgres_status = esg_postgres.postgres_status()
  File "/root/esgf-installer/base/esg_postgres.py", line 404, in postgres_status
    status = esg_functions.call_subprocess("service postgresql status")
  File "/root/esgf-installer/esgf_utilities/esg_functions.py", line 476, in call_subprocess
    raise SubprocessError(command_process_stderr)
esgf_utilities.esg_exceptions.SubprocessError
(esgf-pub) [root@esgf-dev1 esgf-installer]#  service postgresql status
postmaster dead but pid file exists

**Comment by William-Hill** [comment]
I recently changed my subprocess wrapper methods to raise an exception when an error happens.  I'll add the exception handling in --status

**Comment by William-Hill** [comment]
Resolved by 5d01aee64c814cdfa0a0ea8f3a099d010b34edb5
