### ISSUE TITLE
ESGF 3.0 - esg_node.py help or usage message is not clear

### ISSUE THREAD

**Issue by muryanto1** [ESGF/esgf-installer#362]
(esgf-pub) [root@esgf-dev1 esgf-installer]# python esg_node.py --install --type data,index
[]
DEBUG - esg_property_manager.py - 29 - get_property - 03/22/2018 09:27:06 AM - could not find property esg.root.id
DEBUG - esg_property_manager.py - 29 - get_property - 03/22/2018 09:27:06 AM - could not find property esg.root.id
INFO - esg_node.py - 232 - init_connection - 03/22/2018 09:27:06 AM - esg-node initializing...
INFO - esg_node.py - 234 - init_connection - 03/22/2018 09:27:07 AM - esgf-dev1.llnl.gov
install_type: master
usage: esg_node.py [-h] [--install] [--update] [--upgrade]
                   [--install-local-certs] [--generate-esgf-csrs]
                   [--generate-esgf-csrs-ext] [--cert-howto] [--fix-perms]
                   [--type {data,index,idp,compute,all} [{data,index,idp,compute,all} ...]]
                   [--set-type {data,index,idp,compute,all} [{data,index,idp,compute,all} ...]]
                   [--get-type] [--start] [--stop] [--restart] [--status]
                   [--update-sub-installer script_name script_directory]
                   [--update-apache-conf] [-v] [--recommended_setup]
                   [--custom_setup] [--use-local-files] [--devel] [--prod]
esg_node.py: error: argument --type/-t/--flavor: invalid choice: 'data,index' (choose from 'data', 'index', 'idp', 'compute', 'all')

The usage message seems to indicate that I should use comma between the types.

**Comment by sashakames** [comment]
The --type option typically took multiple arguments separated by space, eg "--type index idp data"
