### ISSUE TITLE
ESGF 3.0 installer should skip installing java/postgres/apache...etc..if it is already installed

### ISSUE THREAD

**Issue by muryanto1** [ESGF/esgf-installer#364]
I used auto-installer, and I did:
python esg_node.py --install --type data
python esg_node.py --install --type  index

The 2nd install will fail unless I edit my /esg/config/esgf.properties to say 'n' for the following entries:
install.java = n
install.ant = n
install.postgres = n
install.apache = n
install.tomcat = n

It will be more user friendly if esg_node.py just skip the install of those components if they already exists.

**Comment by sashakames** [comment]
Reviewing this, there is misunderstanding (from inadequate documentation) that you would never use the installer in the fashion above. 

This would change the type 

leads to two issues.
(1) prevent the user or warn that one doesn't do it like that
(2) for upgrades, there is indeed no need to reinstall a component that has not changed.

**Comment by William-Hill** [comment]
I'm planning to fix this issue today. The installer looks for an "install.{component}" entry in the esgf.properties file.  I'm changing it to "update.{component}" to be more clear.  This way an installation will ignore the setup of a component if that component has been previously installed unless "update.{component}" is set to "y" or "yes".

**Comment by William-Hill** [comment]
Which components in particular?  For those components, I could remove the "update.{component}" entry, but check the remote version against the installed version to see if an actual update should be performed.  Depends on everything being properly versioned though

**Comment by sashakames** [comment]
I think most components could be affected, as any web service could be vulnerable to something on a CVE list.
