### ISSUE TITLE
migrate apache to httpd (3.0)

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-installer#367]
Look at esgf-dev1 - uses /etc/sysconfig/httpd 
still uses esgf-httpd.conf

replace LD_LIBRARY_PATH with the correct values  subsitute base python path /opt/esgf/... with /usr/local/conda/envs/esgf-pub/

in esgf-httpd use the correct absolute mod_wsgi.so path,   correct python-path to /usr/local/conda/envs/esgf-pub/  or a virtualenv based on it

Possibly create a separate environment for cog/web - virtualenv

**Comment by William-Hill** [comment]
Resolved with 52658f815a9ec5bb5fd2dac8484074d828c8e38b
