### ISSUE TITLE
ESGF 3.0 alpha failed in setup_postgres()

### ISSUE THREAD

**Issue by muryanto1** [ESGF/esgf-installer#371]
(esgf-pub) [root@esgf-dev1 esgf-installer]# python esg_node.py --install --type data
...
...
*******************************
Setting up Postgres
******************************* 

Checking for postgresql >= 8.4.20 
Postgres not found on system

*******************************
Downloading Postgres
******************************* 

Loaded plugins: fastestmirror, priorities
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: centos.sonn.com
 * epel: mirrors.cat.pdx.edu
 * extras: mirror.sjc02.svwh.net
 * updates: mirror.sjc02.svwh.net
Resolving Dependencies
--> Running transaction check
---> Package postgresql.x86_64 0:8.4.20-8.el6_9 will be installed
--> Processing Dependency: postgresql-libs(x86-64) = 8.4.20-8.el6_9 for package: postgresql-8.4.20-8.el6_9.x86_64
--> Processing Dependency: libpq.so.5()(64bit) for package: postgresql-8.4.20-8.el6_9.x86_64
---> Package postgresql-devel.x86_64 0:8.4.20-8.el6_9 will be installed
---> Package postgresql-server.x86_64 0:8.4.20-8.el6_9 will be installed
--> Running transaction check
---> Package postgresql-libs.x86_64 0:8.4.20-8.el6_9 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                 Arch         Version               Repository     Size
================================================================================
Installing:
 postgresql              x86_64       8.4.20-8.el6_9        updates       2.6 M
 postgresql-devel        x86_64       8.4.20-8.el6_9        updates       816 k
 postgresql-server       x86_64       8.4.20-8.el6_9        updates       3.4 M
Installing for dependencies:
 postgresql-libs         x86_64       8.4.20-8.el6_9        updates       202 k

Transaction Summary
================================================================================
Install       4 Package(s)

Total download size: 7.0 M
Installed size: 32 M
Downloading Packages:
--------------------------------------------------------------------------------
Total                                           1.9 MB/s | 7.0 MB     00:03     
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : postgresql-libs-8.4.20-8.el6_9.x86_64                        1/4 
  Installing : postgresql-8.4.20-8.el6_9.x86_64                             2/4 
  Installing : postgresql-server-8.4.20-8.el6_9.x86_64                      3/4 
  Installing : postgresql-devel-8.4.20-8.el6_9.x86_64                       4/4 
  Verifying  : postgresql-server-8.4.20-8.el6_9.x86_64                      1/4 
  Verifying  : postgresql-devel-8.4.20-8.el6_9.x86_64                       2/4 
  Verifying  : postgresql-libs-8.4.20-8.el6_9.x86_64                        3/4 
  Verifying  : postgresql-8.4.20-8.el6_9.x86_64                             4/4 

Installed:
  postgresql.x86_64 0:8.4.20-8.el6_9                                            
  postgresql-devel.x86_64 0:8.4.20-8.el6_9                                      
  postgresql-server.x86_64 0:8.4.20-8.el6_9                                     

Dependency Installed:
  postgresql-libs.x86_64 0:8.4.20-8.el6_9                                       

Complete!
Initializing database:                                     [  OK  ]
Starting postgresql service:                               [  OK  ]
DEBUG - esg_functions.py - 458 - call_subprocess - 03/29/2018 04:35:39 PM - command_string: service postgresql status
DEBUG - esg_functions.py - 472 - call_subprocess - 03/29/2018 04:35:39 PM - command_process_stdout: postmaster (pid  4219) is running...

DEBUG - esg_functions.py - 473 - call_subprocess - 03/29/2018 04:35:39 PM - command_process_stderr: 
DEBUG - esg_functions.py - 474 - call_subprocess - 03/29/2018 04:35:39 PM - command_process.returncode: 0
Postgres server status: postmaster (pid  4219) is running...

Restarting postgres server
DEBUG - esg_functions.py - 458 - call_subprocess - 03/29/2018 04:35:39 PM - command_string: service postgresql restart
DEBUG - esg_functions.py - 472 - call_subprocess - 03/29/2018 04:36:43 PM - command_process_stdout: Stopping postgresql service: [FAILED]
Starting postgresql service: [  OK  ]

DEBUG - esg_functions.py - 473 - call_subprocess - 03/29/2018 04:36:43 PM - command_process_stderr: 
DEBUG - esg_functions.py - 474 - call_subprocess - 03/29/2018 04:36:43 PM - command_process.returncode: 1
Traceback (most recent call last):
  File "esg_node.py", line 509, in <module>
    main(node_type_list)
  File "esg_node.py", line 453, in main
    system_component_installation(esg_dist_url, node_type_list)
  File "esg_node.py", line 300, in system_component_installation
    esg_postgres.setup_postgres()
  File "/root/esgf-installer/base/esg_postgres.py", line 114, in setup_postgres
    restart_postgres()
  File "/root/esgf-installer/base/esg_postgres.py", line 415, in restart_postgres
    restart_process = esg_functions.call_subprocess("service postgresql restart")
  File "/root/esgf-installer/esgf_utilities/esg_functions.py", line 476, in call_subprocess
    raise SubprocessError(command_process_stderr)
esgf_utilities.esg_exceptions.SubprocessError

**Comment by William-Hill** [comment]
Stopping postgres failed but not sure why.  Has this happened multiple times? @muryanto1

**Comment by muryanto1** [comment]
I just repeated "python esg_node.py --install --type data".
This time, I did not hit the issue this time. I am closing this issue.
