### ISSUE TITLE
Convert code for mirror selection

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#375]
Currently, some of the code is hardcoded to pull from the aims1 mirror.  The user should have the option of choosing which mirror they would like to use.

An option will be added to esgf.properties where a mirror name or "fastest" are valid options.  If the installer encounters one of those options, it will act accordingly. Otherwise, it will prompt the user to choose from a list of distribution mirrors.

**Comment by William-Hill** [comment]
Resolved by 25663575f88dfaa0062d5bf224f0b04b8fd40764

**Comment by pchengi** [comment]
@William-Hill , this sounds very much like the --use-local-mirror option in ESGF 2.6? Have you seen it? Does this do the same thing? If so, we should probably use the same name?

**Comment by William-Hill** [comment]
@pchengi not exactly the same. This is for selecting a remote distribution mirror, which should be the default option.  Using a local mirror is a niche case I imagine.  So I'll implement that in a separate issue, #380
