### ISSUE TITLE
Convert test_globus_services() to Python

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#403]
The test_globus_services() function in esg-globus should be converted to Python.  It should live in the test_globus.py module.

**Comment by William-Hill** [comment]
Has this test been deprecated as well? @sashakames

**Comment by William-Hill** [comment]
Ok, I'll close this particular issue

**Comment by sashakames** [comment]
I don't think its being used.  Globus might be particularly tricky to test internally.  Also myproxy is being retired soon so testing the SLCS CA will be a greater priority.
