### ISSUE TITLE
Download publication test file during setup_publisher

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#416]
When running the publication test (esgtest_publish) post-installation, the test expects a test file to live at /esg/data/test/sftlf.nc.

Add a function that downloads the file when running setup_publisher()

**Comment by sashakames** [comment]
The publication test automatically downloads the file from the mirror, so this isn't needed.  Perhaps there was some other issue?

**Comment by William-Hill** [comment]
@sashakames The problem seems to occur if the test directory (i.e. /esg/data/test) doesn't exist.  
The test subdirectory didn't get created on my installation (I just had /esg/data) and I got the following error:

Set up Publication Test
Checking write permissions for /esg/data/test/sftlf.nc, user root... [FAIL]

Creating the test subdirectory solved the problem though.

**Comment by sashakames** [comment]
I think you were on to something here.  I think the 2.x installer does create ../test in preparation.

**Comment by William-Hill** [comment]
I can reopen and add code to the setup_publisher() function to create that directory. Should be an easy fix.
