### ISSUE TITLE
mail.smtp.host

### ISSUE THREAD

**Issue by mattben** [ESGF/esgf-installer#45]
after an update  esgf.properties is will reset my mail server to:

    mail.smtp.host=smtp.llnl.gov

Is there a way to leave this settings alone? we need it to be:

    mail.smtp.host=nospam.llnl.gov

**Comment by ncaripsl** [comment]
https://github.com/ESGF/esgf-node-manager/commit/827ed4c65900d11c294e08b56eb951327005c902
