### ISSUE TITLE
esgtest_publish failing

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#456]
The publication test for 3.0 is failing.

When attempting to invoke myproxy-logon manually with `myproxy-logon -b -s esgf-dev2.llnl.gov -l rootAdmin -o ~/.globus/certificate-file `, the following error occurs:

Bootstrapping MyProxy server root of trust.
Error authenticating: GSS Major Status: Authentication Failed
GSS Minor Status Error Chain:
globus_gss_assist: Error during context initialization
OpenSSL Error: s3_clnt.c:1178: in library: SSL routines, function SSL3_GET_SERVER_CERTIFICATE: certificate verify failed
globus_gsi_callback_module: Could not verify credential
globus_gsi_callback_module: Can't get the local trusted CA certificate: Cannot find trusted CA certificate with hash ba60fab8 in /root/.globus/certificates

So the certificates are not being added to the .globus/certificates directory.

**Comment by William-Hill** [comment]
Error message from /var/log/messages:

Jul  9 08:48:12 esgf-dev2 myproxy-server[62331]: Connection from 198.128.245.132
Jul  9 08:48:12 esgf-dev2 myproxy-server[62331]: Error authenticating client: Connection closed. 
Jul  9 08:48:12 esgf-dev2 myproxy-server[62331]: Failure: error in myproxy_send() 
Jul  9 08:48:12 esgf-dev2 myproxy-server[62329]: Error authenticating client: Connection closed. 
Jul  9 08:48:12 esgf-dev2 myproxy-server[62329]: Exiting: authentication failed

**Comment by William-Hill** [comment]
Made some fixes but still getting errors.
Running `myproxy-logon -b -v -s esgf-dev2.llnl.gov -l rootAdmin -o ~/.globus/certificate-file ` gives the following output on the esgf-dev2 test server:

MyProxy v6.1 Jun 2018 PAM SASL KRB5 LDAP VOMS OCSP
Attempting to connect to 198.128.245.132:7512 
Successfully connected to esgf-dev2.llnl.gov:7512 
using trusted certificates directory /root/.globus/certificates
Using Host cert file (/etc/grid-security/hostcert.pem), key file (/etc/grid-security/hostkey.pem)
server name: /O=ESGF/OU=ESGF.ORG/CN=esgf-dev2.llnl.gov
checking that server name is acceptable...
server name matches "esgf-dev2.llnl.gov"
authenticated server name is acceptable
Enter MyProxy pass phrase:
requesting trusted certificates download
got cert file: 4b828555.signing_policy 
got cert file: 99eb76fc.0 
got cert file: 1e09d511.0 
got cert file: 598630ad.0 
got cert file: 85cf5865.0 
got cert file: f131b364.0 
got cert file: fe50ad5a.signing_policy 
got cert file: 4f06f81d.0 
got cert file: 241a8801.signing_policy 
got cert file: 7d9c641e.0 
got cert file: d7e8dc79.0 
got cert file: dfc28aa6.0 
got cert file: 812e17de.0 
got cert file: a059cd44.0 
got cert file: ba89ed3b.0 
got cert file: 3d1308eb.0 
got cert file: d1f1d944.signing_policy 
got cert file: b13cc6df.0 
got cert file: 439ce3f7.signing_policy 
got cert file: 99b0865c.0 
got cert file: b204d74a.signing_policy 
got cert file: 157753a5.signing_policy 
got cert file: 8dcb65b2.0 
got cert file: d9be2151.0 
got cert file: 89b6ac3d.signing_policy 
got cert file: 6b99d060.0 
got cert file: 46117fcc.0 
got cert file: c7ab88a4.signing_policy 
got cert file: d919ffd0.0 
got cert file: 0bc342e6.signing_policy 
got cert file: 064e0aa9.0 
got cert file: 530f7122.signing_policy 
got cert file: dfeb0db4.signing_policy 
got cert file: 47671b99.signing_policy 
got cert file: 98cb3a31.0 
got cert file: b1159c4c.0 
got cert file: 4a03b169.signing_policy 
got cert file: fa94b75f.signing_policy 
got cert file: fc5a8f99.signing_policy 
got cert file: 3513523f.0 
got cert file: a059cd44.signing_policy 
got cert file: bc4a46a2.signing_policy 
got cert file: cd6ccc41.signing_policy 
got cert file: 439ce3f7.0 
got cert file: f081611a.0 
got cert file: 1ec4d31a.0 
got cert file: 0597e90c.0 
got cert file: 7ed47087.signing_policy 
got cert file: 1d1427de.signing_policy 
got cert file: cbf06781.0 
got cert file: fc5a8f99.0 
got cert file: 0119347c.0 
got cert file: 530f7122.0 
got cert file: cf320a85.0 
got cert file: fa94b75f.0 
got cert file: 4b828555.0 
got cert file: 157753a5.0 
got cert file: 6d8bb6eb.signing_policy 
got cert file: 2e5ac55d.0 
got cert file: 6ab64010.0 
got cert file: 0597e90c.signing_policy 
got cert file: b13cc6df.signing_policy 
got cert file: 7ed47087.0 
got cert file: 99eb76fc.signing_policy 
got cert file: ba60fab8.0 
got cert file: cf320a85.signing_policy 
got cert file: ba60fab8.signing_policy 
got cert file: 244b5494.0 
got cert file: dfc28aa6.signing_policy 
got cert file: 02265526.0 
got cert file: 09184877.signing_policy 
got cert file: 812e17de.signing_policy 
got cert file: b204d74a.0 
got cert file: 0119347c.signing_policy 
got cert file: 09184877.0 
got cert file: 85bc937c.signing_policy 
got cert file: 46117fcc.signing_policy 
got cert file: cd6ccc41.0 
got cert file: 9d0a75f2.signing_policy 
got cert file: eb99629b.0 
got cert file: d9be2151.signing_policy 
got cert file: 02b2d53d.0 
got cert file: 966293ce.0 
got cert file: a02a928e.signing_policy 
got cert file: 7cef5492.signing_policy 
got cert file: 6107e209.0 
got cert file: ee19250c.signing_policy 
got cert file: 6107e209.signing_policy 
got cert file: dd5d4ea8.0 
Failed to receive credentials.
ERROR from myproxy-server:
Certificate generation failure.
Error accepting delegated credentials: server-side error: check server logs

Checking the log at `/var/log/messages` gives the following:
Aug 21 15:23:32 esgf-dev2 myproxy-server[118709]: Connection from 198.128.245.132
Aug 21 15:23:32 esgf-dev2 myproxy-server[118709]: Authenticated client /O=ESGF/OU=ESGF.ORG/CN=esgf-dev2.llnl.gov
Aug 21 15:24:41 esgf-dev2 myproxy-server[118709]: Received GET request for username rootAdmin
Aug 21 15:24:41 esgf-dev2 PAM_pgsql[118709]: (myproxy) user rootAdmin authenticated.
Aug 21 15:24:41 esgf-dev2 myproxy-server[118709]: PAM authentication succeeded for rootAdmin
Aug 21 15:24:41 esgf-dev2 myproxy-server[118709]: Sending trust roots to /O=ESGF/OU=ESGF.ORG/CN=esgf-dev2.llnl.gov
Aug 21 15:24:41 esgf-dev2 myproxy-server[118709]: Got a cert request for user "rootAdmin", with pubkey hash "0x33ef2353", and lifetime "43200"
Aug 21 15:24:41 esgf-dev2 myproxy-server[118709]: globus_gsi_cert_utils_get_x509_name() failed globus_cert_utils: Error parsing subject name: The subject_string cannot be convert to an X509_NAME, unexpected format Internal cert generation failed CA failed to generate certificate

**Comment by William-Hill** [comment]
There is a file located at `/esg/config/myproxy/myproxy-certificate-mapapp` that allows myproxy-logon to access the cacert to parse the subject name from the certificate.  The path to the file is set in the myproxy-server.config file.  There was a typo in the path to the mapapp file that was causing myproxy-logon to fail when trying to get the subject name from the CA cert

**Comment by William-Hill** [comment]
134116c4aef9f79fbc8190f957c161851d730f8c fixes the typo

**Comment by William-Hill** [comment]
A new error is occurring with the myproxy-logon step:

`myproxy-logon -b -T -v -s esgf-dev2.llnl.gov -l rootAdmin -o ~/.globus/certificate-file 
MyProxy v6.1 Aug 2018 PAM SASL KRB5 LDAP VOMS OCSP
Attempting to connect to 198.128.245.132:7512 
Successfully connected to esgf-dev2.llnl.gov:7512 
using trusted certificates directory /root/.globus/certificates
Using Host cert file (/etc/grid-security/hostcert.pem), key file (/etc/grid-security/hostkey.pem)
Bootstrapping MyProxy server root of trust.
/etc/grid-security/certificates/ exists. Updating.
Attempting to connect to 198.128.245.132:7512 
Successfully connected to esgf-dev2.llnl.gov:7512 
renamed /etc/grid-security/certificates/ba60fab8.0.tmp to /etc/grid-security/certificates/ba60fab8.0
wrote trusted certificate to /etc/grid-security/certificates/ba60fab8.0
renamed /etc/grid-security/certificates/ba60fab8.signing_policy.tmp to /etc/grid-security/certificates/ba60fab8.signing_policy
wrote trusted certificate policy to /etc/grid-security/certificates/ba60fab8.signing_policy
New trusted MyProxy server: /O=ESGF/OU=ESGF.ORG/CN=esgf-dev2.llnl.gov
New trusted CA (ba60fab8.0): /O=ESGF/OU=ESGF.ORG/CN=esgf-dev2.llnl.gov-CA
MyProxy v6.1 Aug 2018 PAM SASL KRB5 LDAP VOMS OCSP
Attempting to connect to 198.128.245.132:7512 
Successfully connected to esgf-dev2.llnl.gov:7512 
using trusted certificates directory /root/.globus/certificates
Using Host cert file (/etc/grid-security/hostcert.pem), key file (/etc/grid-security/hostkey.pem)
Error authenticating: GSS Major Status: Authentication Failed
GSS Minor Status Error Chain:
globus_gss_assist: Error during context initialization
OpenSSL Error: s3_clnt.c:1178: in library: SSL routines, function SSL3_GET_SERVER_CERTIFICATE: certificate verify failed
globus_gsi_callback_module: Could not verify credential
globus_gsi_callback_module: Can't get the local trusted CA certificate: Untrusted self-signed certificate in chain with hash ba60fab8`

The hash of the self-signed cert it is attempting to use comes from taking the hash of the value found for the key certificate_issuer_cert in myproxy-server.config

**Comment by nathanlcarlson** [comment]
@William-Hill with recent changes resolving #597 #589  and #482 I believe this is resolved now as well.

**Comment by sashakames** [comment]
I've seen enough positive evidence that esgtest_publish works given a proper installation

**Comment by William-Hill** [comment]
@nathanlcarlson @sashakames Great. Do we have a tag cut denoting that the publication test is working.  Because we can look at marking that as beta release

**Comment by nathanlcarlson** [comment]
@William-Hill Technically the publication test will not work from a fresh install until #601 is resolved. Perhaps after that has been addressed and is tested we could do the release. @sashakames had a discussion about how #601 should be resolved, but I am unsure what the conclusion was.

**Comment by William-Hill** [comment]
@nathanlcarlson @sashakames If it was decided to add that the fix should just be added to CoG like the rest of the group management, it can just be added to my fork of CoG
