### ISSUE TITLE
esgf-dashboard setup in 3.0

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-installer#462]
Add python module for the dashboard.  this includes:
Geo-IP (binary)
esgf-dashboard-ip (binary)
esgf-dashboard schema from .egg (have refactored module for this?)
esgf-stats-api (java webapp)

**Comment by nathanlcarlson** [comment]
I have started this with #528 and #536. There remain some errors regarding `liblzma.5.so` at the startup of this service `/usr/local/esgf-dashboard-ip/bin/ip.service start`.

**Comment by nathanlcarlson** [comment]
#615 documents the issues encountered during the process of resolving this.

**Comment by nathanlcarlson** [comment]
With the resolution of #615, withstanding any unseen problems, I believe this is resolved as well.
