### ISSUE TITLE
Investigate install Python modules from Conda instead of pip

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#466]
In esg_bootstrap.sh, there is a step in which Python modules are fetched from conda and a separate step in which modules are fetched from pip.

Investigate in the modules fetched from pip are available via conda.  If so, we can just fetch from conda and remove the pip step.

**Comment by sashakames** [comment]
There are required modules that will only be available with pip.  No way around that.  Some might be available and the 2.x installer is a source for that information.

**Comment by nathanlcarlson** [comment]
Closing issue as @sashakames has said this will not possible as many ESGF packages exist only in pip.

**Comment by sashakames** [comment]
While it won't be possible to eliminate pip entirely, its possible that some pip-installed packages in 3.0 could be found in conda.  One easy place to start is to look at the esg-node bash script and see if there are packages already identified to use "conda install" that had previously used pip.  If none, maybe there are others that could be moved, eg. for CoG.

**Comment by nathanlcarlson** [comment]
All of the packages that could be moved to the conda install have been. Some of these packages ended up being removed entirely as they were dependencies of components that were going to be installed later and if the components are not installed it is preferred to not have the unneeded dependencies installed.
