### ISSUE TITLE
Ensure CMIP6 service clients are deployed in 3.0 and are functional

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-installer#468]
Depends-on:  regular publication test works.   Consider steps run in esg-node to deploy these, eg. cdf2sim, esgfpid, cmor, etc.

There is no "formal" cmip6 test but guidelines to test this can be found in a google doc:

https://docs.google.com/document/d/1PMylUmByTa0kyUI-nyJD708pKDVosxWWSFpx4LyReCs/edit

**Comment by nathanlcarlson** [comment]
There were a couple issues encountered with `cmor`, but these are out of our hands and we may just need to await the next stable release. I am going to resolve this as the steps as described in the above google doc were completed successfully.
