### ISSUE TITLE
esgf 3.x installer failed in "Setting up Java 1.8.0_162" step

### ISSUE THREAD

**Issue by muryanto1** [ESGF/esgf-installer#471]
`
*******************************
Setting up Java 1.8.0_162
******************************* 

Don't see java distribution file /usr/local/src/esgf/workbench/esg/jdk1.8.0_162-64.tar.gz either
Downloading Java from  http://aims1.llnl.  [37mDEBUG   [0m | [37mesg_functions.py - 307 - download_update - 08/15/2018 01:35:28 PM - local file : jdk1.8.0_162-64.tar.gz[0m
  [37mDEBUG   [0m | [37mesg_functions.py - 308 - download_update - 08/15/2018 01:35:28 PM - remote file: http://aims1.llnl.gov/esgf/dist/java/1.8.0_162/jdk1.8.0_162-64.tar.gz[0m
  [37mDEBUG   [0m | [37mesg_functions.py - 73 - get_md5sum - 08/15/2018 01:37:29 PM - local_file_md5 : 781e3779f0c134fb548bde8b8e715e90[0m
Cannot contact esgf-dev1: java.lang.InterruptedException
  [37mDEBUG   [0m | [37mpybash.py - 100 - symlink_force - 08/15/2018 01:39:02 PM - Creating symlink from /usr/local/jdk1.8.0_162 -> /usr/local/java[0m
gov/esgf/dist/java/1.8.0_162/jdk1.8.0_162-64.tar.gz
DEBUG: Checking to see if jdk1.8.0_162-64.tar.gz is in a git repository...
DEBUG: jdk1.8.0_162-64.tar.gz does not exist yet, allowing creation
 WARNING: Could not find local file jdk1.8.0_162-64.tar.gz
Fetching file from http://aims1.llnl.gov/esgf/dist/java/1.8.0_162/jdk1.8.0_162-64.tar.gz -to-> jdk1.8.0_162-64.tar.gz
jdk1.8.0_162-64.tar.gz checksum [VERIFIED]
Extracting Java tarfile jdk1.8.0_162-64.tar.gz
Extracting jdk1.8.0_162-64.tar.gz ->  /usr/local
Could not stream subprocess output
stream_subprocess_output error: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "esg_node.py", line 489, in <module>
    main()
  File "esg_node.py", line 371, in main
    system_component_installation(esg_dist_url, node_type_list)
  File "esg_node.py", line 213, in system_component_installation
    esg_java.setup_java()
  File "/home/jenkins/repos/esgf-installer/base/esg_java.py", line 114, in setup_java
    set_default_java()
  File "/home/jenkins/repos/esgf-installer/base/esg_java.py", line 20, in set_default_java
    "alternatives --install /usr/bin/java java /usr/local/java/bin/java 3")
  File "/home/jenkins/repos/esgf-installer/esgf_utilities/esg_functions.py", line 404, in stream_subprocess_output
    process = subprocess.Popen(shlex.split(command_string), stdout=subprocess.PIPE)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

**Comment by nathanlcarlson** [comment]
I have encountered this as well. Am working on it now.

**Comment by nathanlcarlson** [comment]
python_devel now contains this fix
