### ISSUE TITLE
Convert the certificate_mapapp file to Python

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#482]
The certificate_mapapp file is used to provide a way for myproxy-logon to access the intended CA cert to be used. 
From  http://grid.ncsa.illinois.edu/myproxy/ca/:

> "The myproxy-server administrator must also configure the myproxy-server with the CA key, other CA attributes, and a method for mapping MyProxy usernames to Distinguished Names (DNs) in the signed certificates. Three mapping methods are supported: certificate_mapfile, which follows the Globus Toolkit grid-mapfile format, certificate_mapapp, which provides a general-purpose call-out interface, and LDAP. "

It is currently written in Bash and could benefit to being converted to Python for clarity and testability.

There are references to a Java binary called ESGOpenIDRetriever within the file.  This binary appears to try to fetch an OpenID name for the database. This may can be replaced with using pure Python (such as using pyschopg2).

The file is downloaded from a mirror (located at https://aims1.llnl.gov/esgf/dist/devel/globus/myproxy/myproxy-certificate-mapapp) during the myproxy setup.

More information about the certificate mapapp can be found at http://grid.ncsa.illinois.edu/myproxy/man/myproxy-server.config.5.html

**Comment by nathanlcarlson** [comment]
@William-Hill I have opened #589, which would be resolved by resolving this. Do we want to the Python version of this to do the query itself, or should it call the Java application? Also, how should it get access to the needed modules (primarily `psycopg2`)? Let me know what you think.

**Comment by nathanlcarlson** [comment]
@William-Hill I just re-read the issue and see pure python, in which case how could we get access to`psycopg2`? Would it be terrible to have a bash script which activates the esgf-pub env and then calls the python script?

**Comment by sashakames** [comment]
Agreed thats probably the safe bet.  Alternatively, globus would need to run in an environment where it can get the correct python and modules, and no side effects along the way.

**Comment by William-Hill** [comment]
@nathanlcarlson Having a bash script that activates esgf-pub and delegates to a Python script should be fine
