### ISSUE TITLE
esgf 3.x installer failed in _choose_organization_name()

### ISSUE THREAD

**Issue by muryanto1** [ESGF/esgf-installer#487]
-------------------------------------------------------
Welcome to the ESGF Node installation program! :-)
-------------------------------------------------------
What is the name of your organization? [llnl]: Traceback (most recent call last):
  File "esg_node.py", line 441, in <module>
    main()
  File "esg_node.py", line 318, in main
    esg_questionnaire.initial_setup_questionnaire()
  File "/home/jenkins/repos/esgf-installer/esgf_utilities/esg_questionnaire.py", line 221, in initial_setup_questionnaire
    _choose_organization_name()
  File "/home/jenkins/repos/esgf-installer/esgf_utilities/esg_questionnaire.py", line 71, in _choose_organization_name
    org_name_input = raw_input("What is the name of your organization? [{default_org_name}]: ".format(default_org_name=default_org_name)) or default_org_name
EOFError: EOF when reading a line

**Comment by nathanlcarlson** [comment]
Have you started working on this? If not, go ahead and assign it to me as it is closely related to #486

**Comment by nathanlcarlson** [comment]
A change was made in PR #485 to the property manager. Empty values are no longer accepted and the program will prompt for input. This is what occurred for the "esg.org.name" property
```
esg.org.name = ""
```
A system for allowing values to be empty if that is a valid entry for the property is being developed.
