### ISSUE TITLE
Not really an Issues

### ISSUE THREAD

**Issue by mattben** [ESGF/esgf-installer#53]
I have written a pre installer and uninstall python script. I'm not sure if you would find them helpful or would like to use them as a base for improvements.

https://github.com/webshootertk/utilitybelt/blob/master/esgf_preinstaller.py

https://github.com/webshootertk/utilitybelt/blob/master/esgf_uninstaller.py

**Comment by pchengi** [comment]
@mattben , can you add this to git@github.com:ESGF/esgf-utils.git and then close this issue, after you've added it? We'll look it up when we can.
