### ISSUE TITLE
Use templated web.xml file for Thredds

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#545]
There's a templated web.xml file hosted on the mirror that is used to help install the logging filters.  That web.xml file should be added to the repo and used when setting up the filters.

**Comment by nathanlcarlson** [comment]
@William-Hill I've come across this as well. I may take care of it, sound good?

**Comment by William-Hill** [comment]
@nathanlcarlson  I've already started work on it.  Pull request should be out soon

**Comment by William-Hill** [comment]
Resolved by #565
