### ISSUE TITLE
NetCDF-4 C library not present

### ISSUE THREAD

**Issue by nathanlcarlson** [ESGF/esgf-installer#576]
`/usr/local/tomcat/logs/catalina.out` reports the following warnings.
```
WARN  [localhost-startStop-1] (TdsContext.java:getPropertyDir():508) - TdsContext.init(): "tds.upload.dir" property isn't defined.
WARN  [localhost-startStop-1] (TdsContext.java:getPropertyFile():554) - TdsContext.init(): "tds.upload.form" property isn't defined.
WARN  [localhost-startStop-1] (TdsContext.java:getPropertyDir():508) - TdsContext.init(): "tds.download.dir" property isn't defined.
WARN  [localhost-startStop-1] (TdsContext.java:getPropertyFile():554) - TdsContext.init(): "tds.download.form" property isn't defined.
WARN  [localhost-startStop-1] (Nc4Iosp.java:load():157) - Nc4Iosp: NetCDF-4 C library not present (jna_path='null', libname='netcdf').
java.lang.UnsatisfiedLinkError: Unable to load library 'netcdf': Native library (linux-x86-64/libnetcdf.so) not found in resource path ([file:/usr/local/apache-tomcat-8.5.20/webapps/thredds/WEB-INF/classes/, ...
```

**Comment by nathanlcarlson** [comment]
`yum install netcdf netcdf-devel` resolved this.

**Comment by nathanlcarlson** [comment]
Leaving this open until it is added to the installer.

**Comment by nathanlcarlson** [comment]
@sashakames  Do you know if those missing properties are to be specified at the command line during tomcat start up like `-Dtds.download.dir` or within a config file? Also, what should the values be?

**Comment by nathanlcarlson** [comment]
@sashakames It looks like that are to be set in `/usr/local/tomcat/bin/setenv.sh`. Is that correct?

**Comment by nathanlcarlson** [comment]
[This TDS site](https://www.unidata.ucar.edu/blogs/developer/entry/upload-and-download-support-for) mentions that these properties need to be defined for upload and download capabilities. I am not sure how this has been done in the past.

**Comment by sashakames** [comment]
I noticed the PR for installing netCDF via yum.  We don't do this in 2.x and I think there's a good reason, that NetCDF is too closely coupled to many of the tools eg. CDAT that are deployed via other means.  We could end up with a version conflict.  I think to get THREDDS working its better to try to see what's different from 2.x, where presumably we don't have this problem.

**Comment by sashakames** [comment]
Thinking more about this, in 2.x TDS likely runs in an environment where NetCDF is installed.  Perhaps its missing now in 3.0?

**Comment by nathanlcarlson** [comment]
It is just a warning, it looks like thredds can start without it.

**Comment by nathanlcarlson** [comment]
TDS's website talks about this library [here](https://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/netcdf4Clibrary.html)

**Comment by sashakames** [comment]
source /path/to/conda/bin/activate esgf-pub # if not already
conda list # you should find NetCDF there

**Comment by nathanlcarlson** [comment]
There are a couple `netcdf-fortran` and `netCDF4`. What really needs to be present I think is
```
ls /usr/local/conda/envs/esgf-pub/lib/ | grep libnetcdf.so
```
I uninstalled to `netcdf-fortran` and `libnetcdf.so` remained, so the package that installs it is `netCDF4`. And it is present, it seems then the LD_LIBRARY_PATH does not include `/usr/local/conda/envs/esgf-pub/lib`.
