### ISSUE TITLE
The "rootAdmin" user is not added to the correct publisher groups

### ISSUE THREAD

**Issue by nathanlcarlson** [ESGF/esgf-installer#601]
The "rootAdmin" user needs to be added to the "wheel" group of the local node by default so it has permission to publish and unpublish.

**Comment by nathanlcarlson** [comment]
This is done with the SQL below
```
INSERT INTO esgf_security.permission VALUES (1, 1, 1, true);
```

**Comment by sashakames** [comment]
We were debating of whether to add this to CoG after the user gets created or just run as an add-on.

**Comment by nathanlcarlson** [comment]
Yea, since all user creation and group/role management goes through CoG on the node postinstall, it would be strange to have this one exception where the installer does it.

**Comment by nathanlcarlson** [comment]
Not only strange, perhaps dangerous.

**Comment by nathanlcarlson** [comment]
I created PR https://github.com/William-Hill/COG/pull/4 on @William-Hill 's COG fork to address this.

**Comment by William-Hill** [comment]
Just merged the PR on my CoG fork

**Comment by nathanlcarlson** [comment]
PR https://github.com/William-Hill/COG/pull/5 officially resolves this, as long as @William-Hill 's COG fork (branch "ESGF_3.0") is used.
