### ISSUE TITLE
Refactor add_tomcat_user()

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#629]
In Thredds.py, the add_tomcat_user() function is very clunky.  It makes a call to add_another_user() which checks for a property in esgf.properties.  This should be redesigned to where the tomcat.user key in esgf.properties can accept a comma separated list of users and then parse that list to create the users.

**Comment by sashakames** [comment]
What is the use case for more than one user?  Not to say it shouldn't be done but so far I'm not aware of this need in our deployment.

**Comment by William-Hill** [comment]
@sashakames It's part of the classic installer in the setup_tds() function.  I really don't see the use case of it but I left it in because it was in 2.x.  If you think it isn't used, I can remove it altogether

**Comment by sashakames** [comment]
I remember the interface now.  I think its reasonable to leave the implementation to future work if a need arises.

**Comment by William-Hill** [comment]
@sashakames  Ok, I'll remove the code for adding additional users for now.
