### ISSUE TITLE
Create migration backup script

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-installer#652]
When migrating from 2.x to 3.0, we should provide a mechanism to safely backup existing data and configurations so that functionality and integrity is preserved.  This script can be run by the bootstrap if detects an existing 2.x installation (searching for existence of /usr/local/bin/esg-node and grepping script_maj_version).  A potential option is to run the post installation tests to determine if the node is in working order before beginning the backup.

Some of the relevant directories and files that should be backed up:
/esg/config
/esg/data (dependant on size of data and disk space)
/usr/local/cog_config
/var/lib/pgsql/data

**Comment by William-Hill** [comment]
@nathanlcarlson I added you as an assignee as well because I don't know how much work you have already done towards this and don't want to step on your toes

**Comment by nathanlcarlson** [comment]
@William-Hill I have not done anything on this.

**Comment by William-Hill** [comment]
Resolved as part of #674
