### ISSUE TITLE
publisher and cog fail to install

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-installer#69]
Updating a data node and the installer doesn't update esgcet because of a github connectivity problem.  Unfortunately this is not apparent until later.  Somehow, it reverted v 2.12.1 which is older than the previous version altogether.  

Additionally with this datanode, the hessian url in esg.ini got changed (can this even happen?) to something in IPSL.  

if there's a problem with curl, cog won't install. In this case the libcurl that the installer uses is missing https.  Not using esg.env you can git clone cog with the default libcurl from your os which has https.   It would be helpful if a problem with the cog installation is detected so we can attend to it.

**Comment by ncaripsl** [comment]
Could you please tell what was the github connectivity problem?

The hessian url variable uses your esgf index peer which is the IPSL test federation index node by default for esgf-test peer group and pcmdi9 for esgf-prod peer group.

You mean it is not possible to clone any github.com repo after having sourced /etc/esg.env on this node? Could you paste the error you got and give the git and curl path and version the installer uses in this case?

**Comment by sashakames** [comment]
[root@pcmdi9 ~]# git clone https://github.com/EarthSystemCoG/COG
Initialized empty Git repository in /root/COG/.git/
error: Protocol https not supported or disabled in libcurl while accessing https://github.com/EarthSystemCoG/COG/info/refs

[root@pcmdi9 ~]# curl --version
curl 7.22.0 (x86_64-unknown-linux-gnu) libcurl/7.22.0 zlib/1.2.3 libidn/1.18
Protocols: dict file ftp gopher http imap ldap pop3 rtsp smtp telnet tftp 
Features: IDN IPv6 Largefile libz 

https is indeed missing.   Not the case on other nodes

 
root@pcmdi9 ~]# curl --version
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz 

Looking at ldd traces, the uvcdat/X/bin/curl was not built with ssl.  But this seems to be only on pcmdi9.     Given that curl is distributed with uvcdat, we may get the fix when uvcdat is upgraded.

Perhaps a worthwhile test in the installer would be verification that curl does support https.
