### ISSUE TITLE
Need to test and plan upgrade to Java 8

### ISSUE THREAD

**Issue by ncaripsl** [ESGF/esgf-installer#70]
For ESGF 1.9 or 2.0?

**Comment by pchengi** [comment]
The changes to get Apache before Tomcat have been very much self contained
and less invasive than feared earlier. We can afford to go with one more
change in 1.9, if you want to push it through.

/Prashanth

**Comment by LucaCinquini** [comment]
I would still recommend one change at the time, so my suggestion would be 2.0.... We could plan on a 2.0 by late spring...
