### ISSUE TITLE
Need to tell uvcdat not to build curl

### ISSUE THREAD

**Issue by ncaripsl** [ESGF/esgf-installer#71]
Since ESGF relies on a system curl. The uvcdat one has to be removed. Charles says CMakeLists.txt has to be modified. 

If you know for sure you have curl, simply patch uvcdat install to not
build curl, look for
include(curl)
in CMakeLists.txt at the top of uvcdat repo and comment it out.

I can send a patch if you don't find it.

C.

**Comment by sashakames** [comment]
Looks like the uvcdat rpm doesn't have curl.  So this is a non-issue now
