### ISSUE TITLE
esgf-dashboard

### ISSUE THREAD

**Issue by jackask** [ESGF/esgf-installer#717]
When installing the http://distrib-coffee.ipsl.jussieu.fr/pub/esgf/dist/2.8/4/, it comes up the error:
https://pypi.org/simple/esgf-dashboard/  404 Not Found.

Is there anybody who meets the same error? thanks a lot.

**Comment by sashakames** [comment]
Dear @jackask please consider using the esgf-ansible installer.  http://esgf.github.io/esgf-ansible/

**Comment by jackask** [comment]
I consider using the esgf-ansible installer.  Thanks friends.
