### ISSUE TITLE
OpenSSL man error on clean install

### ISSUE THREAD

**Issue by AndrewIOM** [ESGF/esgf-installer#72]
When trying to set up a data node on a clean virtual machine (CentOS) I get the following error when the script attempts to build OpenSSL:

 Failed at line 315 if statement…
	installing man1/smime.1
	smime.pod around line 272: Expected text after =item, not a number
	smime.pod around line 276: Expected text after =item, not a number
	smime.pod around line 280: Expected text after =item, not a number
	smime.pod around line 285: Expected text after =item, not a number
	smime.pod around line 289: Expected text after =item, not a number
	POD document had syntax errors at /bin/pod2man line 69.

I have also attempted install on Ubuntu 15.04, which yields the same error. Both systems have latest available OpenSSL install present (1.0.1e). 

Replacing the build statement with 'true' in within the if block allows the install to bypass this step and run all the way through.

**Comment by ncaripsl** [comment]
The ESGF software stack v1.8.1 can be installed on CentOS, RedHat or Scientific Linux version 5 and 6 but not on Ubuntu. Please make sure you have installed all the requirements and followed the proper installation procedure at https://github.com/ESGF/esgf-installer/wiki/ESGF-Installation-From-scratch. I would say you are probably missing some ExtUtils packages.

**Comment by AndrewIOM** [comment]
I realised that the fresh CentOS VM I was using was based on V7. On another fresh VM based on 6.6 this error does not occur. Must be something in the newer OS' that breaks the install here. Thanks
