### ISSUE TITLE
fix esg-node --test

### ISSUE THREAD

**Issue by pchengi** [ESGF/esgf-installer#85]
esg-node --test makes lots of globus function calls refering to old globus binary locations, and fails.
Ex:
GridFTP - BDM Test... [bdm]/usr/local/bin/esg-globus: line 909: /usr/local/globus/bin/globus-url-copy: No such file or directory
[FAIL]

/usr/local/bin/esg-node: line 2730: /usr/local/globus/bin/myproxy-logon: No such file or directory
 ERROR: MyProxy not setup properly.  Unable to execute command.

**Comment by lukaszlacinski** [comment]
The issue has been fixed in https://github.com/ESGF/esgf-installer/commit/6aa312df85c06472c2314dc0f2c1c2799b42306d#diff-410b32368e4174ffcdc6150f3c3342d8 and https://github.com/ESGF/esgf-installer/commit/97642dfe4dc1eaf59cbf2a1dca571fbb3d26946c#diff-410b32368e4174ffcdc6150f3c3342d8.

**Comment by sashakames** [comment]
Testing now considered for 3.0.  Superseded by new issue
